// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using task_V2.Models;

namespace task_V2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("task_V2.Models.Gradovi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImeGrada")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Gradovi");
                });

            modelBuilder.Entity("task_V2.Models.Kandidati", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImeKandidata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kratica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Kandidati");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ImeKandidata = "Donald Trump",
                            Kratica = "DT"
                        },
                        new
                        {
                            ID = 2,
                            ImeKandidata = "Hillary Clinton",
                            Kratica = "HC"
                        },
                        new
                        {
                            ID = 3,
                            ImeKandidata = " Joe Biden",
                            Kratica = "JB"
                        },
                        new
                        {
                            ID = 4,
                            ImeKandidata = "John F. Kennedy",
                            Kratica = "JFK"
                        },
                        new
                        {
                            ID = 5,
                            ImeKandidata = "Jack Randall",
                            Kratica = "JR"
                        });
                });

            modelBuilder.Entity("task_V2.Models.Rezultati", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojGlasova")
                        .HasColumnType("int");

                    b.Property<int>("GradoviID")
                        .HasColumnType("int");

                    b.Property<int>("KandidatiID")
                        .HasColumnType("int");

                    b.Property<decimal>("Procenat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("isGreska")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("GradoviID");

                    b.HasIndex("KandidatiID");

                    b.ToTable("Rezultati");
                });

            modelBuilder.Entity("task_V2.Models.Rezultati", b =>
                {
                    b.HasOne("task_V2.Models.Gradovi", "Grad")
                        .WithMany()
                        .HasForeignKey("GradoviID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("task_V2.Models.Kandidati", "Kandidat")
                        .WithMany()
                        .HasForeignKey("KandidatiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
